export function getFrameworkTemplates(framework: string) {
  if (framework === 'nextjs') {
    return `### BASE TEMPLATES (NEXT.JS)
Use these exact templates for essential files. **Output them FIRST** in fenced blocks with paths. Copy verbatim.

⚠️ IMPORT RULE FOR NEXT.JS: ALWAYS use RELATIVE imports. NEVER use "@/" aliases.
- app/page.tsx importing from components/ → use: import X from '../components/X'
- app/dashboard/page.tsx importing from components/ → use: import X from '../../components/X'
- components/Header.tsx importing from lib/ → use: import X from '../lib/X'
Count the directory levels and use the correct number of "../" dots!
❌ WRONG: import TaskCard from '@/components/TaskCard'
✅ RIGHT:  import TaskCard from '../components/TaskCard'

package.json:
\`\`\`json file="package.json"
{
  "name": "nextjs-project",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "next": "14.2.14",
    "lucide-react": "^0.454.0",
    "framer-motion": "^11.11.11",
    "clsx": "^2.1.1",
    "tailwind-merge": "^2.5.4"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.4.19",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
}
\`\`\`

tailwind.config.ts:
\`\`\`ts file="tailwind.config.ts"
import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
export default config;
\`\`\`

postcss.config.js:
\`\`\`js file="postcss.config.js"
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
\`\`\`

app/layout.tsx:
\`\`\`tsx file="app/layout.tsx"
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next.js App",
  description: "Generated by AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
\`\`\`

app/page.tsx (Entry point):
This is the main file of the site.
\`\`\`tsx file="app/page.tsx"
import React from 'react'

export default function Home() {
  return (
    <div className="p-4 bg-gray-100 text-center min-h-screen">
      <h1 className="text-2xl font-bold text-blue-500">Hello, Tailwind CSS with Next.js!</h1>
      <p className="mt-2 text-gray-700">This is your new app.</p>
    </div>
  )
}
\`\`\`

app/globals.css:
\`\`\`css file="app/globals.css"
@tailwind base;
@tailwind components;
@tailwind utilities;
\`\`\``
  }

  if (framework === 'vue') {
    return `### BASE TEMPLATES (VUE)
Use these exact templates for essential files. **Output them FIRST** in fenced blocks with paths. Copy verbatim.
package.json:
\`\`\`json file="package.json"
{
  "name": "vue-project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc -b && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.5.10"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.1.4",
    "autoprefixer": "^10.4.20",
    "postcss": "^8.4.47",
    "tailwindcss": "^3.4.13",
    "typescript": "^5.5.3",
    "vite": "^5.4.8",
    "vue-tsc": "^2.1.6"
  }
}
\`\`\`

vite.config.ts:
\`\`\`ts file="vite.config.ts"
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
})
\`\`\`

tailwind.config.ts:
\`\`\`ts file="tailwind.config.ts"
import type { Config } from 'tailwindcss'

export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
} satisfies Config
\`\`\`

postcss.config.js:
\`\`\`js file="postcss.config.js"
export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
\`\`\`

index.html:
\`\`\`html file="index.html"
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + Vue</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
\`\`\`

src/main.ts:
\`\`\`ts file="src/main.ts"
import { createApp } from 'vue'
import './style.css'
import App from './App.vue'

createApp(App).mount('#app')
\`\`\`

src/style.css:
\`\`\`css file="src/style.css"
@tailwind base;
@tailwind components;
@tailwind utilities;
\`\`\`

src/App.vue (Entry point):
This is the main file of the site.
\`\`\`vue file="src/App.vue"
<script setup lang="ts">
</script>

<template>
  <div class="p-4 bg-gray-100 text-center min-h-screen">
    <h1 class="text-2xl font-bold text-blue-500">Hello, Tailwind CSS with Vue!</h1>
    <p class="mt-2 text-gray-700">This is your new app.</p>
  </div>
</template>
\`\`\``
  }

  // Default: Vite (React)
  return `### BASE TEMPLATES (VITE + REACT)
Use these exact templates for essential files. **Output them FIRST** in fenced blocks with paths. Copy verbatim. These include critical files like src/utils/ to prevent import errors. **Vite-Only: No Next.js templates.**

CRITICAL IMPORT RULE: In Vite projects, you MAY use "@/" path aliases (e.g. import X from '@/components/X') ONLY because the vite.config.ts and tsconfig.json below configure this alias. ALWAYS output both config files below when generating a new Vite project. Never use "@/" in a project that doesn't have these config files.

package.json (Base with react, vite, tailwind essentials):
\`\`\`json file="package.json"
{
  "name": "vite-project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "test": "vitest"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "lucide-react": "^0.454.0",
    "react-router-dom": "^6.26.2",
    "@tanstack/react-query": "^5.56.2",
    "framer-motion": "^11.11.11",
    "clsx": "^2.1.1",
    "tailwind-merge": "^2.5.4",
    "zustand": "^5.0.0-rc.2"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.11",
    "@types/react-dom": "^18.3.1",
    "@vitejs/plugin-react": "^4.3.2",
    "autoprefixer": "^10.4.20",
    "postcss": "^8.4.47",
    "tailwindcss": "^3.4.13",
    "vite": "^5.4.8",
    "vitest": "^2.1.2"
  }
}
\`\`\`

vite.config.ts:
\`\`\`ts file="vite.config.ts"
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  server: {
    headers: {
      // Allow external images (wixstatic, framerusercontent, ctfassets, etc.)
      // to load inside the WebContainer preview iframe
      "Cross-Origin-Embedder-Policy": "unsafe-none",
      "Cross-Origin-Resource-Policy": "cross-origin",
    },
  },
})
\`\`\`

tsconfig.json:
\`\`\`json file="tsconfig.json"
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noFallthroughCasesInSwitch": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
\`\`\`

tailwind.config.ts:
\`\`\`ts file="tailwind.config.ts"
import type { Config } from 'tailwindcss'

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
} satisfies Config
\`\`\`

postcss.config.js:
\`\`\`js file="postcss.config.js"
export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
\`\`\`

index.html:
\`\`\`html file="index.html"
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + React</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
\`\`\`

src/App.tsx (Entry point):
This is the main file of the site, in which you will enter the data, edit it, and this is the file on which you make the changes within the landing page.
\`\`\`tsx file="src/App.tsx"
import React from 'react'
import './index.css'

export default function App() {
  return (
    <div className="p-4 bg-gray-100 text-center">
      <h1 className="text-2xl font-bold text-blue-500">Hello, Tailwind CSS with Vite!</h1>
      <p className="mt-2 text-gray-700">This is a live code editor.</p>
    </div>
  )
}
\`\`\`

README.md (Project setup and run instructions):
\`\`\`md file="README.md"
# AI Site Project

## Setup
npm install

## Run Dev
npm run dev

## Build
npm run build

## Preview
npm run preview

## Test
npm run test
\`\`\``
}
